# promptfooconfig.yaml

description: "GitHubEval: Benchmarking LLM generation of precise curl commands for GitHub API (Top 12 most-starred 'airbnb' repositories)."

providers:
  # 1. openrouter:openai/gpt-4o-mini with max_tokens: 1024
  - id: openrouter:openai/gpt-4o-mini
    config:
      max_tokens: 1024
  # 2. openrouter:openai/gpt-4.1-nano with max_tokens: 1024
  - id: openrouter:openai/gpt-4.1-nano
    config:
      max_tokens: 1024
  # 3. openrouter:google/gemini-2.0-flash-lite-001
  - openrouter:google/gemini-2.0-flash-lite-001

prompts:
  - |
    Generate a complete, single-line curl command to fetch ONLY the top 12 most-starred repositories from the 'airbnb' organization using the GitHub API. 
    The command must include the necessary header for authorization, using the placeholder '$API_KEY' for the token. 
    Do not include any explanations, introductory phrases, or markdown fences (```). Output only the command.

tests:
  - name: fetch_top_12_airbnb_repos
    vars:
      org: "airbnb"
      limit: "12"
      sort_by: "stars"
      direction: "desc"
    
    assertions:
      # Assertion 1: Uses the correct GitHub API endpoint for the organization's repositories
      - contains-all:
        values:
        - "https://api.github.com/orgs/{{org}}/repos"
      # Assertion 2: Limits the results to exactly 12 repositories
      - contains-all:
        values:
        - "per_page={{limit}}"
      # Assertion 3: Sorts the repositories by stars
      - contains-all:
        values:
        - "sort={{sort_by}}"
      # Assertion 4: Uses descending order for the sort
      - contains-all:
        values:
        - "direction={{direction}}"
      # Assertion 5: Includes proper authorization using the API key placeholder
      - contains-all:
        values:
        - "Authorization: Bearer $API_KEY"
      # Assertion 6: LLM-based rubric for overall correctness and directness
      - llm-rubric:
        instruction: |
          Critically evaluate the output. The response MUST be a single, complete, and immediately runnable shell command (curl) that performs the requested GitHub API call.
          The response should contain NO extraneous text, no markdown code fences, and no explanations.
          It must correctly combine the API endpoint, the 'per_page=12', 'sort=stars', 'direction=desc' query parameters, and the 'Authorization: Bearer $API_KEY' header.
        schema:
        type: object
        properties:
          quality:
          type: number
          minimum: 1
          maximum: 1
        required: [quality]
        additionalProperties: false